// import { combineReducers } from "redux";
// import { GET_PRODUCTS } from "./actionType";

export const GET_PRODUCTS = "GET_PRODUCTS";

const array = [
  {
    url: "https://www.adidas.com/us/five-ten-kestrel-lace-mountain-bike-shoes/BC0770.html",
    name: "Five Ten Kestrel Lace Mountain Bike Shoes",
    sku: "BC0770",
    selling_price: 150,
    original_price: "",
    currency: "USD",
    availability: "InStock",
    color: "Grey",
    category: "Shoes",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Women/Shoes",
    description:
      "Lace up and get after it. The Five Ten Kestrel Lace Mountain Bike Shoes offer efficient pedal power with low-profile style. The wide platform is compatible with all clipless pedals and offers high-friction grip on and off the bike. You'll find the find comfort and versatility for extended trail rides and afterwork hot laps alike.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/2b04943c525e4909a7a5a9fa0116153d_9366/Five_Ten_Kestrel_Lace_Mountain_Bike_Shoes_Grey_BC0770_01_standard.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.8,
    reviews_count: 4,
    crawled_at: "2021-10-23 17:50:17.423830",
  },
  {
    url: "https://www.adidas.com/us/mexico-away-jersey/GC7946.html",
    name: "Mexico Away Jersey",
    sku: "GC7946",
    selling_price: 70,
    original_price: "",
    currency: "USD",
    availability: "InStock",
    color: "White",
    category: "Clothing",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Kids/Clothing",
    description:
      "Clean and crisp, this adidas Mexico Away Jersey for juniors displays a design that began life in an artist's studio. Soft, quick-drying fabric keeps you comfortable. Standing out on the chest, a team badge lets fans show pride in their soccer team.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/d3485a6cd3fd42c19083ab1000fee858_9366/Mexico_Away_Jersey_White_GC7946_43_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.9,
    reviews_count: 42,
    crawled_at: "2021-10-23 17:50:17.530834",
  },
  {
    url: "https://www.adidas.com/us/five-ten-hiangle-pro-competition-climbing-shoes/FV4744.html",
    name: "Five Ten Hiangle Pro Competition Climbing Shoes",
    sku: "FV4744",
    selling_price: 160,
    original_price: "",
    currency: "USD",
    availability: "InStock",
    color: "Black",
    category: "Shoes",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Five Ten/Shoes",
    description:
      "The Hiangle Pro takes on the classic shape of the original Hiangle with the addition of a seamless outsole wrapping around the toes, allowing for maximum rubber contact when tackling the most challenging boulder problems.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/c6221d2435b8455eaa7aac8d011dcc7a_9366/Five_Ten_Hiangle_Pro_Competition_Climbing_Shoes_Black_FV4744_HM4.jpg",
    country: "USA",
    language: "en",
    average_rating: 3.7,
    reviews_count: 7,
    crawled_at: "2021-10-23 17:50:17.615054",
  },
  {
    url: "https://www.adidas.com/us/mesh-broken-stripe-polo-shirt/GM0239.html",
    name: "Mesh Broken-Stripe Polo Shirt",
    sku: "GM0239",
    selling_price: 65,
    original_price: "",
    currency: "USD",
    availability: "InStock",
    color: "Blue",
    category: "Clothing",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Men/Clothing",
    description:
      "Step up to the tee relaxed. This adidas golf polo shirt lets you focus on accurate drives and putts. Four-way stretch matches the body's natural movements. Breathable fabric keeps you comfortable spring, summer and fall. Recycled materials are one step towards reducing plastic waste.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/1e31163790704db59eefac44006c056c_9366/Mesh_Broken-Stripe_Polo_Shirt_Blue_GM0239_42_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.7,
    reviews_count: 11,
    crawled_at: "2021-10-23 17:50:17.702680",
  },
  {
    url: "https://www.adidas.com/us/eqt-spikeless-golf-shoes/FX7449.html",
    name: "EQT Spikeless Golf Shoes",
    sku: "FX7449",
    selling_price: 110,
    original_price: "",
    currency: "USD",
    availability: "InStock",
    color: "Grey",
    category: "Shoes",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Women/Shoes",
    description:
      "Put comfort first. These adidas spikeless golf shoes combine a Bounce midsole and a Boost heel for a lightweight, responsive feel that helps you convert bogie's to birdies. They repel water to keep your feet dry through wet fairways. The versatile rubber outsole ensures easy transitions from your final putt to cold drinks at the clubhouse. Recycled materials are one step towards reducing plastic waste.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/f49e6ede5a1248f1b189ad1200ed941b_9366/EQT_Spikeless_Golf_Shoes_Grey_FX7449_HM4.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.9,
    reviews_count: 30,
    crawled_at: "2021-10-23 17:50:17.783493",
  },
  {
    url: "https://www.adidas.com/us/adicross-hybrid-shorts/GM5505.html",
    name: "Adicross Hybrid Shorts",
    sku: "GM5505",
    selling_price: 80,
    original_price: "",
    currency: "USD",
    availability: "InStock",
    color: "Black",
    category: "Clothing",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Men/Clothing",
    description:
      "On the golf course, comfort is an essential component of keeping your concentration locked in on each shot. Stay focused as the temperature heats up with these ultra-lightweight adidas shorts. Move naturally through your round from the first tee to the 18th green. Then head for the clubhouse feeling ready for whatever comes next.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/9779f7b8650b42edbe62ad3d0106129a_9366/Adicross_Hybrid_Shorts_Black_GM5505_HM3.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.5,
    reviews_count: 17,
    crawled_at: "2021-10-23 17:50:17.860269",
  },
  {
    url: "https://www.adidas.com/us/tiro-21-windbreaker/GP4975.html",
    name: "Tiro 21 Windbreaker",
    sku: "GP4975",
    selling_price: 60,
    original_price: "",
    currency: "USD",
    availability: "InStock",
    color: "Black",
    category: "Clothing",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Kids/Clothing",
    description:
      "You can't always be a force of nature in soccer training. So when the intensity drops and the winds pick up, this juniors' adidas Tiro 21 Windbreaker has you covered. Moisture-absorbing AEROREADY and a mesh lining keep you dry. The streamlined silhouette ensures nothing gets in the way of your ball skills on the touchline.\n\nThis product is made with recycled content as part of our ambition to end plastic waste.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/a92321113ca8409fa818ac4500fa1573_9366/Tiro_21_Windbreaker_Black_GP4975_43_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.5,
    reviews_count: 16,
    crawled_at: "2021-10-23 17:50:17.942359",
  },
  {
    url: "https://www.adidas.com/us/classic-3-stripes-swimsuit/FS3923.html",
    name: "Classic 3-Stripes Swimsuit",
    sku: "FS3923",
    selling_price: 40,
    original_price: "",
    currency: "USD",
    availability: "InStock",
    color: "Black",
    category: "Clothing",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Women/Clothing",
    description:
      "You can show your concern for the health of the oceans while you increase your fitness in the pool. This adidas swimsuit is designed for comfort and support. Soft and fully lined, it's made with yarn spun from recycled materials. Iconic 3-Stripes tape on the sides gives it a sporty and classic look.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/59fdce4cb6a24a28a4fcabd60115d73e_9366/Classic_3-Stripes_Swimsuit_Black_FS3923_43_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.5,
    reviews_count: 35,
    crawled_at: "2021-10-23 17:50:18.136849",
  },
  {
    url: "https://www.adidas.com/us/tiro-21-windbreaker/GP4967.html",
    name: "Tiro 21 Windbreaker",
    sku: "GP4967",
    selling_price: 65,
    original_price: "",
    currency: "USD",
    availability: "InStock",
    color: "Black",
    category: "Clothing",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Men/Clothing",
    description:
      "You can't always be a force of nature in soccer training. So when the intensity drops and the breeze picks up, this adidas Tiro 21 Windbreaker has you covered on the sidelines. Moisture-absorbing AEROREADY and a mesh lining help keep you dry while you're sheltering. The streamlined silhouette means you can stay mobile while you're waiting for the gusts to die down.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/46d523a753ff49d2b0bdac560163264c_9366/Tiro_21_Windbreaker_Black_GP4967_42_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.8,
    reviews_count: 66,
    crawled_at: "2021-10-23 17:50:18.581061",
  },
  {
    url: "https://www.adidas.com/us/formotion-sculpt-biker-short-tights/GL1127.html",
    name: "Formotion Sculpt Biker Short Tights",
    sku: "GL1127",
    selling_price: 60,
    original_price: "",
    currency: "USD",
    availability: "InStock",
    color: "Black",
    category: "Clothing",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Women/Clothing",
    description:
      "Sometimes confidence comes in a surprising form. These adidas short tights have a unique sculpted shape to hold you in and targeted compression zones that support your muscles as you bend and stretch. If a compression look is not your thing, order a size up. An adaptive FORMOTION design follows your natural movement for a better fit and greater comfort in motion. A high-rise waist helps you focus, even before class begins.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/35be8830cc4042288b75ac5d00204fd5_9366/Formotion_Sculpt_Biker_Short_Tights_Black_GL1127_43_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.4,
    reviews_count: 26,
    crawled_at: "2021-10-23 17:50:18.666644",
  },
  {
    url: "https://www.adidas.com/us/athletic-cushioned-crew-socks-6-pairs/B93219.html",
    name: "Athletic Cushioned Crew Socks 6 Pairs",
    sku: "B93219",
    selling_price: 20,
    original_price: "",
    currency: "USD",
    availability: "InStock",
    color: "White",
    category: "Accessories",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Men/Accessories",
    description:
      "Stop searching for the lost match to your favorite socks. With six pairs of matching socks, you'll always have a set. These adidas crew socks support your feet with foot-hugging arch support. The stretch blend pulls moisture away from the skin to keep feet feeling dry.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/c1d1f661da8e4e4f8ee9ab56011d3cd9_9366/Athletic_Cushioned_Crew_Socks_6_Pairs_White_B93219_03_standard.jpg",
    country: "USA",
    language: "en",
    average_rating: 4,
    reviews_count: 5,
    crawled_at: "2021-10-23 17:50:19.329862",
  },
  {
    url: "https://www.adidas.com/us/fast-primeblue-tee/H32236.html",
    name: "Fast Primeblue Tee",
    sku: "H32236",
    selling_price: 32,
    original_price: "$40",
    currency: "USD",
    availability: "InStock",
    color: "White",
    category: "Clothing",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Women/Clothing",
    description:
      "Unleash your speed. This adidas leopard-print t-shirt gives you something bold to wear while running across the finish line. The cropped, boxy cut is about easy motion as much as style. AEROREADY keeps you dry and focused through the final stretch.\n\nThis product is made with Primeblue, a high-performance recycled material made in part with Parley Ocean Plastic.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/29ad21a938ef4a33b5ecacfc014cc084_9366/Fast_Primeblue_Tee_White_H32236_42_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.8,
    reviews_count: 13,
    crawled_at: "2021-10-23 17:52:29.474656",
  },
  {
    url: "https://www.adidas.com/us/fast-primeblue-tee/H11276.html",
    name: "Fast Primeblue Tee",
    sku: "H11276",
    selling_price: 32,
    original_price: "$40",
    currency: "USD",
    availability: "InStock",
    color: "Green",
    category: "Clothing",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Women/Clothing",
    description:
      "Unleash your speed. This adidas leopard-print t-shirt gives you something bold to wear while running across the finish line. The cropped, boxy cut is about easy motion as much as style. AEROREADY keeps you dry and focused through the final stretch.\n\nThis product is made with Primeblue, a high-performance recycled material made in part with Parley Ocean Plastic.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/dd4dd365a34e4b8fa72aad030144818a_9366/Fast_Primeblue_Tee_Green_H11276_43_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.8,
    reviews_count: 13,
    crawled_at: "2021-10-23 17:52:29.570424",
  },
  {
    url: "https://www.adidas.com/us/short-piping-high-waist-tights/H17923.html",
    name: "Short Piping High-Waist Tights",
    sku: "H17923",
    selling_price: 28,
    original_price: "$40",
    currency: "USD",
    availability: "InStock",
    color: "Black",
    category: "Clothing",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Women/Clothing",
    description:
      "What you wear sets the tone for what you do. When you pull on these adidas short tights, it's all about ease. Soft stretchy cotton flatters your shape, and 3-Stripes pack a sporty punch. If your plans change, your outfit doesn't have to. Swap out that sweatshirt for a crop top as you transition from the couch to the dance floor. Easy. \n\nBy buying cotton products from us, you're supporting more sustainable cotton farming.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/b5ff054356fa4d68a3a4ad57007f2afe_9366/Short_Piping_High-Waist_Tights_Black_H17923_42_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 5,
    reviews_count: 5,
    crawled_at: "2021-10-23 17:52:30.058173",
  },
  {
    url: "https://www.adidas.com/us/adicolor-essentials-trefoil-swim-shorts/H35501.html",
    name: "Adicolor Essentials Trefoil Swim Shorts",
    sku: "H35501",
    selling_price: 28,
    original_price: "$35",
    currency: "USD",
    availability: "InStock",
    color: "Yellow",
    category: "Clothing",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Men/Clothing",
    description:
      "Always ready to jump in the water. Pull on these perfectly classic adidas swim shorts and head out feeling carefree and ready for whatever comes your way. A back pocket holds your essentials. Just make sure to take them out when you find a pool to jump in.\n\nThis product is made with Primegreen, a series of high-performance recycled materials.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/d2911a0d914045028971ad1000f61523_9366/Adicolor_Essentials_Trefoil_Swim_Shorts_Yellow_H35501_42_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.8,
    reviews_count: 23,
    crawled_at: "2021-10-23 17:52:30.150359",
  },
  {
    url: "https://www.adidas.com/us/marble-logo-graphic-print-hoodie/H22628.html",
    name: "Marble Logo Graphic Print Hoodie",
    sku: "H22628",
    selling_price: 32,
    original_price: "$45",
    currency: "USD",
    availability: "InStock",
    color: "White",
    category: "Clothing",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Kids/Clothing",
    description:
      "OK, so pink-and-blue marble print might not technically be a \"neutral.\" But you'll find yourself reaching for this juniors' adidas hoodie so frequently that it might as well be. It's soft on the inside, swirly on the outside and magically perfect with everything else in your closet.\n\nBy buying cotton products from us, you're supporting more sustainable cotton farming.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/bc5a7eb77ff647f8b9afad0b01079cae_9366/Marble_Logo_Graphic_Print_Hoodie_White_H22628_43_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 5,
    reviews_count: 8,
    crawled_at: "2021-10-23 17:52:30.341100",
  },
  {
    url: "https://www.adidas.com/us/supernova-plus-shoes/S42718.html",
    name: "Supernova+ Shoes",
    sku: "S42718",
    selling_price: 84,
    original_price: "$120",
    currency: "USD",
    availability: "InStock",
    color: "Blue",
    category: "Shoes",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Women/Shoes",
    description:
      "When you've achieved your goals and it's time to set new ones, these adidas running shoes help you reach the next summit. Flexible Bounce cushioning combines with Boost in the heel and forefoot to keep your transitions smooth and return energy to your stride. \n\nThis product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/5ff54d48660d471fabdfad20005b08df_9366/Supernova+_Shoes_Blue_S42718_43_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.3,
    reviews_count: 151,
    crawled_at: "2021-10-23 17:52:30.427155",
  },
  {
    url: "https://www.adidas.com/us/copa-sense.3-laceless-firm-ground-cleats/FX1983.html",
    name: "Copa Sense.3 Laceless Firm Ground Cleats",
    sku: "FX1983",
    selling_price: 49,
    original_price: "$70",
    currency: "USD",
    availability: "InStock",
    color: "White",
    category: "Shoes",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Kids/Shoes",
    description:
      "Some players talk a good game. But the best ones feel it. Get in touch with your senses and elevate your play in Copa Sense. These juniors' adidas soccer cleats feature a synthetic upper for a smooth first touch. The laceless construction molds around the contours of your foot for a comfortable fit. The outsole delivers high traction on firm ground.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/d9509ff87727497f9cf5acb000dd33ba_9366/Copa_Sense.3_Laceless_Firm_Ground_Cleats_White_FX1983_42_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.8,
    reviews_count: 43,
    crawled_at: "2021-10-23 17:52:30.509618",
  },
  {
    url: "https://www.adidas.com/us/jacquard-trefoil-crew-socks-2-pairs/H32424.html",
    name: "Jacquard Trefoil Crew Socks 2 Pairs",
    sku: "H32424",
    selling_price: 12,
    original_price: "$14",
    currency: "USD",
    availability: "InStock",
    color: "White",
    category: "Accessories",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Originals/Accessories",
    description:
      "Simple. Classic. A little bit unexpected. Pull on these socks with sneakers or slides, and keep your feet comfortable in light, stretchy fabric. The essential style transforms up close with semi-sheer Trefoils that rep your adidas pride.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/527153a081d044d99270ad130101661b_9366/Jacquard_Trefoil_Crew_Socks_2_Pairs_White_H32424_42_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 5,
    reviews_count: 9,
    crawled_at: "2021-10-23 17:52:30.597460",
  },
  {
    url: "https://www.adidas.com/us/eq21-run-shoes/FX2247.html",
    name: "EQ21 Run Shoes",
    sku: "FX2247",
    selling_price: 44,
    original_price: "$55",
    currency: "USD",
    availability: "InStock",
    color: "Blue",
    category: "Shoes",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Kids/Shoes",
    description:
      "Whether you run for sport, for training or just for fun, lace up in these juniors' adidas shoes to tackle your running goals. The durable upper gives you a snug yet comfortable fit. The lightweight Bounce midsole with Lightstrike cushions every step from heel-strike to toe-off.\n\nThis product is made with Primegreen, a series of high-performance recycled materials.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/7770ecea6f1c45499147ac6801160c76_9366/EQ21_Run_Shoes_Blue_FX2247_42_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.7,
    reviews_count: 177,
    crawled_at: "2021-10-23 17:52:30.702508",
  },
  {
    url: "https://www.adidas.com/us/eq21-run-shoes/GV9935.html",
    name: "EQ21 Run Shoes",
    sku: "GV9935",
    selling_price: 48,
    original_price: "$60",
    currency: "USD",
    availability: "InStock",
    color: "Grey",
    category: "Shoes",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Kids/Shoes",
    description:
      "Whether you run for sport, for training or just for fun, lace up in these juniors' adidas shoes to tackle your running goals. The durable upper gives you a snug yet comfortable fit. The lightweight Bounce midsole with Lightstrike cushions every step from heel-strike to toe-off.\n\nThis product is made with Primegreen, a series of high-performance recycled materials.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/ad9a9328b8b841ce9d24ad4301742edd_9366/EQ21_Run_Shoes_Grey_GV9935_42_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.7,
    reviews_count: 177,
    crawled_at: "2021-10-23 17:52:30.900842",
  },
  {
    url: "https://www.adidas.com/us/x-ghosted.3-firm-ground-cleats/FW6935.html",
    name: "X Ghosted.3 Firm Ground Cleats",
    sku: "FW6935",
    selling_price: 42,
    original_price: "$60",
    currency: "USD",
    availability: "InStock",
    color: "Pink",
    category: "Shoes",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Kids/Shoes",
    description:
      "The only thing that makes defenders sweat more than seeing you on the pitch? Not seeing you at all. Pull on X Ghosted and discover next-level speed. The stretchy tongue on these juniors' adidas soccer cleats means you'll get into them in record time. Their lightweight mesh upper hugs your feet so you're securely strapped in for every sprint. The low-cut silhouette with signature Clawcollar shape locks your foot in for match-long stability and support.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/94d640a98dab4ec59096ac7500f41ff7_9366/X_Ghosted.3_Firm_Ground_Cleats_Pink_FW6935_42_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.7,
    reviews_count: 68,
    crawled_at: "2021-10-23 17:52:31.084333",
  },
  {
    url: "https://www.adidas.com/us/supernova-plus-shoes/S42721.html",
    name: "Supernova+ Shoes",
    sku: "S42721",
    selling_price: 84,
    original_price: "$120",
    currency: "USD",
    availability: "InStock",
    color: "Grey",
    category: "Shoes",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Women/Shoes",
    description:
      "When you've achieved your goals and it's time to set new ones, these adidas running shoes help you reach the next summit. Flexible Bounce cushioning combines with Boost in the heel and forefoot to keep your transitions smooth and return energy to your stride. \n\nThis product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/d94ace784bc8476b9f2aad0b01065f07_9366/Supernova+_Shoes_Grey_S42721_42_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.3,
    reviews_count: 151,
    crawled_at: "2021-10-23 17:52:31.166082",
  },
  {
    url: "https://www.adidas.com/us/qt-racer-sport-shoes/GW4844.html",
    name: "QT Racer Sport Shoes",
    sku: "GW4844",
    selling_price: 52,
    original_price: "$65",
    currency: "USD",
    availability: "InStock",
    color: "White",
    category: "Shoes",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Women/Shoes",
    description:
      "These adidas shoes give you a smooth ride all day long, from your morning run to afternoon errands and then a backyard hangout at night. The Lightmotion midsole delivers super-lightweight cushioning you'll truly appreciate as the hours pass. \n\nThis product is made with Primeblue, a high-performance recycled material made in part with Parley Ocean Plastic. 50% of the upper is textile, 75% of the textile is Primeblue yarn. No virgin polyester.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/5187c5b18d48422eacd1ad1600b2e5e9_9366/QT_Racer_Sport_Shoes_White_GW4844_42_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.4,
    reviews_count: 454,
    crawled_at: "2021-10-23 17:52:31.358185",
  },
  {
    url: "https://www.adidas.com/us/supernova-plus-shoes/FX2858.html",
    name: "Supernova+ Shoes",
    sku: "FX2858",
    selling_price: 72,
    original_price: "$120",
    currency: "USD",
    availability: "InStock",
    color: "White",
    category: "Shoes",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Women/Shoes",
    description:
      "Take off. Touch down. Repeat. These adidas running shoes ensure soft landings and propulsive energy to help you go the distance. A combination of Boost and Bounce in the midsole provides the ideal mix of energy return and spring. The seamless build wraps around your foot, keeping it secure, ventilated and comfortable.\n\nThis product is made with Primegreen, a series of high-performance recycled materials.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/bd461c422e6543febf74ac24013628d2_9366/Supernova+_Shoes_White_FX2858_43_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.3,
    reviews_count: 151,
    crawled_at: "2021-10-23 17:52:31.937924",
  },
  {
    url: "https://www.adidas.com/us/choigo-shoes/H00667.html",
    name: "Choigo Shoes",
    sku: "H00667",
    selling_price: 70,
    original_price: "$100",
    currency: "USD",
    availability: "InStock",
    color: "White",
    category: "Shoes",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Women/Shoes",
    description:
      "If you want drama, the bold female track and field crew of the '80s knew all about it. Their bright outfits were second only to their unmatched speed. These adidas Choigo Shoes pay tribute to those game changers. The distinctive sneakers make an impression with pops of Color, a lace toggle and a lifted outsole. And of course, performance spikes.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/c7b09c1e90c847e98b36ad2401485f91_9366/Choigo_Shoes_White_H00667_42_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.7,
    reviews_count: 135,
    crawled_at: "2021-10-23 17:52:32.014973",
  },
  {
    url: "https://www.adidas.com/us/daily-3.0-shoes/GZ7705.html",
    name: "Daily 3.0 Shoes",
    sku: "GZ7705",
    selling_price: 35,
    original_price: "$50",
    currency: "USD",
    availability: "InStock",
    color: "Black",
    category: "Shoes",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Kids/Shoes",
    description:
      "The style is in the details of the Daily 3.0 Shoes. Stitched-down 3-Stripes along the midfoot give an elegant nod to adidas heritage, and the rubber outsole brings a vulcanized look, playing up the retro skate shoe vibe. As versatile as they are comfortable, these kids' shoes beg to be worn every day, every way.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/a502d3349d1b4882a661ad180146adc9_9366/Daily_3.0_Shoes_Black_GZ7705_42_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.7,
    reviews_count: 190,
    crawled_at: "2021-10-23 17:52:32.208426",
  },
  {
    url: "https://www.adidas.com/us/daily-3.0-shoes/GZ7706.html",
    name: "Daily 3.0 Shoes",
    sku: "GZ7706",
    selling_price: 40,
    original_price: "$50",
    currency: "USD",
    availability: "InStock",
    color: "Pink",
    category: "Shoes",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Kids/Shoes",
    description:
      "The style is in the details of the Daily 3.0 Shoes. Stitched-down 3-Stripes along the midfoot give an elegant nod to adidas heritage, and the rubber outsole brings a vulcanized look, playing up the retro skate shoe vibe. As versatile as they are comfortable, these kids' shoes beg to be worn every day, every way.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/87b8f37ec5d141b2a3ebad180146ebdd_9366/Daily_3.0_Shoes_Pink_GZ7706_42_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.7,
    reviews_count: 190,
    crawled_at: "2021-10-23 17:52:32.293622",
  },
  {
    url: "https://www.adidas.com/us/choigo-shoes/FY6503.html",
    name: "Choigo Shoes",
    sku: "FY6503",
    selling_price: 70,
    original_price: "$100",
    currency: "USD",
    availability: "InStock",
    color: "Black",
    category: "Shoes",
    source: "adidas United States",
    source_website: "https://www.adidas.com",
    breadcrumbs: "Women/Shoes",
    description:
      "Take your style to bold new heights. Throw in some retro attitude while you're at it. Inspired by the style of '80s track athletes, these adidas Choigo Shoes stand out with a textile and mesh upper, performance spikes and a high-rise outsole. Stand tall and enjoy the walking-on-clouds comfort.",
    brand: "adidas",
    images:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/f5c1cdbae7e44cb2b622ac7701590a0a_9366/Choigo_Shoes_Black_FY6503_42_detail.jpg",
    country: "USA",
    language: "en",
    average_rating: 4.7,
    reviews_count: 135,
    crawled_at: "2021-10-23 17:52:32.398104",
  },
];

export const getProducts = () => {
  return function (dispatch) {
    const allProducts = array;
    dispatch({ type: GET_PRODUCTS, payload: allProducts });
  };
};
